### ISSUE TITLE
gravatar doesn't show on android 

### ISSUE THREAD

**Issue by valn1** [lwhiteley/react-native-gravatar#2]
the gravatar avatar doesn't display on android, it works just fine on ios, but doen't work at all for android.
is there any fix for that?

      <ScrollView>
            <View style={{
                borderBottomWidth:1,
                borderColor:'#ddd'
                }}>
                <Gravatar style={{
                    width:60,
                    borderWidth: 3,
                    height:60,
                    borderRadius:30,
                    margin:20,
                    backgroundColor:'#333',
                    padding:30
                }}
                    options={{
                         email:'valdelivaz001@gmail.com',
                         secure: true
                    }}/>
            </View>
            <DrawerItems {...props}/>
        </ScrollView>

![Screenshot_1612870639](https://user-images.githubusercontent.com/40465512/107358373-0ecd7180-6ab2-11eb-9353-9d5236b6f59d.png)

**Comment by valn1** [comment]
the avatar should be above "today"

**Comment by lwhiteley** [comment]
That is quite odd. There shouldn't be any platform specific code. Did you check if the request itself was successful. It's not enough to go on.

**Comment by valn1** [comment]
i fixed it, it had nothing to do with gravatar, sorry
